# Generated by Django 5.0.1 on 2024-03-09 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_gastoextra_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoextra',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gastoextra',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.producto'),
        ),
    ]
